version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ~./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      # - run:
      #     name: Clean Project Directory
      #     command: ./gradlew clean
      # - run:
      #     name: Create debug apk
      #     command: ./gradlew assembleDebug
      - save_cache:
          paths:
            - ~/.gradle
          key: app-build

  test:
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Unit Tests
          command: ./gradlew jacocoTestReport
      - store_artifacts:
          path: app/build/reports
          destination: reports



    # static-analysis:

    # release:



workflows:
  scoreIndicator:
    jobs:
      - build
      # - test:
      #     requires: [build]
      # - static-analysis:
      #     requires: [build]
      # - release:
      #     requires: [static-analysis]