version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Print some stuff
          command: |
            pwd
            ls -lrt

workflows:
  scoreIndicator:
    jobs:
      - build