version: 2.1

defaults: &defaults
  docker:
    - image: circleci/android:api-30-node
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  createEnvironment:
    steps:
      - checkout
      - run
          name: Generate sonar-project.properties
          command: |
            touch sonar-project.properties
            echo sonar.projectKey=$sonar_projectKey >> sonar-project.properties
            echo sonar.host.url=$sonar_host_url >> sonar-project.properties
            echo sonar.login=$sonar_projectKey >> sonar-project.properties
            echo sonar.junit.reportPaths=$sonar_junit_reportPaths >> sonar-project.properties
            echo sonar.coverage.jacoco.xmlReportPaths=$sonar_coverage_jacoco_xmlReportPaths >> sonar-project.properties
            echo sonar.kotlin.detekt.reportPaths=$sonar_kotlin_detekt_reportPaths >> sonar-project.properties
            echo sonar.dependencyCheck.htmlReportPath=$sonar_dependencyCheck_htmlReportPath >> sonar-project.properties
      - run:
          name: Print sonar-project.properties contents
          command: |
            pwd
            echo sonar-project.properties

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: [ app-build ]
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: app-build

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "scoreindicator/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "scoreindicator/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports

workflows:
  scoreIndicator:
    jobs:
      - createEnvironment
#      - build
#      - test